### PR TITLE
fix(headerbar): Include apps with no display name in filter

### LINKED ISSUE #263: HeaderBar: Search box does not filter some apps
In https://github.com/dhis2/ui-widgets/blob/master/src/HeaderBar/Apps.js#L171 only ``displayName`` is used to filter the app list.

Instead both ``name`` and ``displayName`` should be used.

```js
apps.filter(({ displayName, name }) => {
    const appName = displayName || name;
    return filter.length > 0
        ? appName.toLowerCase().match(filter.toLowerCase())
        : true
})
```

### PR DESCRIPTION
**Pull request by SferaDev**
* **Issue:** Closes #263

### CODE REVIEW

File: src/HeaderBar/Apps.js [hunk 1]
```diff
@@ -168,9 +168,10 @@ function List({ apps, filter }) {
     return (
         <div data-test="headerbar-apps-menu-list">
             {apps
-                .filter(({ displayName }) => {
+                .filter(({ displayName, name }) => {
+                    const appName = displayName || name;
```
Comment (varl) [inline src/HeaderBar/Apps.js]: Moving this check up here means that we should be able to remove the check here: https://github.com/dhis2/ui-widgets/pull/274/files#diff-a8543f56f1a36f99128200467054b8d3R180

Comment (SferaDev) [reply src/HeaderBar/Apps.js]: Yeah, I repeated the check because I did not want to add a new map only to join the ``displayName || name``. Filtering a ReactNode is probably not a good idea.

Comment (varl) [reply src/HeaderBar/Apps.js]: Alright, cool. I prefer duplicating the check (the current implementation) in that case. :+1:
